# Everything in this section will be available as an environment variable
#db_username = "Jane"
#db_password = "mypassword"
apikey = "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxZWM4ZjY0MWU4ZmVmMzA4ZDViMDFhYzI1NjNkNWIyMiIsIm5iZiI6MTUwMDY3NTk1NS45Mjk5OTk4LCJzdWIiOiI1OTcyN2Y2NjkyNTE0MTdmYTYwMTkxMzkiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.OY6KiLw4IcTZK1LZ0w5mptaYjobAaocUHO-WaPLhPQc"


# You can also add other sections if you like.
# The contents of sections as shown below will not become environment variables,
# but they'll be easily accessible from within Streamlit anyway as we show
# later in this doc.
#[my_other_secrets]
#things_i_like = ["Streamlit", "Python"]
